Write-Host "Current environment variables:"
Write-Host "SH306_APPNAME (SH360 Application Name): $env:SH360_APPNAME"
Write-Host "AKS_SUB (Azure subscription): $env:AKS_SUB"
Write-Host "AKS_RG (Resource Group): $env:AKS_RG"
Write-Host "AKS_NAME (AKS Name): $env:AKS_NAME"
Write-Host "ACR_NAME (ACR Name): $env:ACR_NAME"
Write-Host "AKS_REGION (Azure Region): $env:AKS_REGION"
Write-Host "SPN_CLIENT_ID (Client ID): $env:SPN_CLIENT_ID"
Write-Host "SPN_PW (Client Password): $env:SPN_PW"
Write-Host "----------------------------------------------------------"